server:
  port: 8080
spring:
  # 配置文件上传大小限制
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
minio:
  host: http://139.159.237.2:9000 # 访问地址
  accessKey: 1UQ3vMCnUgMTi2apQ7EU # 登录账号
  secretKey: rxz21gGQ4TnmtzPwHxC425HPhD43Jku7WbGMLUsV # 登录账号密码
  bucketName: sky # 文件桶的名称
  bucket: public  # 权限